# Generated by Django 6.0.7 on 2026-07-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=35, null=True)),
                ('sku', models.CharField(max_length=12, unique=True)),
                ('category', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
