# Generated by Django 6.0.7 on 2026-07-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('receipt_header', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_footer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
